zim_cert_auth_denied_index:
    path:     /denied
    defaults: { _controller: ZimCertAuthBundle:AccessDenied:index }

zim_cert_auth_denied_restore:
    path:     /denied/resore
    defaults: { _controller: ZimCertAuthBundle:AccessDenied:restore }

zim_cert_auth_denied_blocked:
    path:     /denied/resore
    defaults: { _controller: ZimCertAuthBundle:AccessDenied:blocked }